Database:
  DBType: mysql
  Username: root  # 填写你的数据库账号
  Password: linfp0813
  Host: 127.0.0.1:3306
  DBName: web_service
  # TablePrefix: blog_
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30

Server:
  RunMode: debug
  HttpPort: 8000
  ReadTimeout: 6000000000
  WriteTimeout: 6000000000

JWT:
  Secret: eddycjy
  Issuer: blog-service
  Expire: 7200

Email:
  Host: smtp.qq.com
  Port: 465
  UserName: 281484683@qq.com
  Password: xdxswyevrzolcaeb
  IsSSL: true
  From: 281484683@qq.com